/**
 * Generates public/sitemap.xml at build time.
 *
 * `lastmod` used to be typed by hand — it sat at 2025-10-24 for months, which
 * tells crawlers "nothing here has changed" and discourages re-indexing. Any
 * value a human has to remember to update is a value that goes stale, so it's
 * derived from the build instead.
 *
 * Runs automatically via the `prebuild` npm script.
 */
import { writeFileSync, mkdirSync } from "node:fs";
import { dirname, resolve } from "node:path";
import { fileURLToPath } from "node:url";

const SITE = "https://sidick.vercel.app";
const LANGUAGES = ["en", "fr"];

/** Add a route here when you add one to App.jsx. */
const ROUTES = [
  { path: "/", priority: "1.0" },
  { path: "/projects/web", priority: "0.8" },
  { path: "/projects/mobile", priority: "0.8" },
  { path: "/projects/design", priority: "0.8" },
  { path: "/projects/ai", priority: "0.8" },
];

const lastmod = new Date().toISOString().slice(0, 10);

const alternates = (path) =>
  [
    ...LANGUAGES.map(
      (l) =>
        `    <xhtml:link rel="alternate" hreflang="${l}" href="${SITE}${path}?lang=${l}"/>`,
    ),
    `    <xhtml:link rel="alternate" hreflang="x-default" href="${SITE}${path}"/>`,
  ].join("\n");

const entries = ROUTES.flatMap(({ path, priority }) =>
  // One entry per language. The hreflang annotations must be reciprocal —
  // Google ignores a set where the alternates don't point back at each other.
  LANGUAGES.map(
    (lang) => `  <url>
    <loc>${SITE}${path}?lang=${lang}</loc>
${alternates(path)}
    <lastmod>${lastmod}</lastmod>
    <changefreq>monthly</changefreq>
    <priority>${priority}</priority>
  </url>`,
  ),
);

const xml = `<?xml version="1.0" encoding="UTF-8"?>
<!-- Generated by scripts/generate-sitemap.mjs — do not edit by hand. -->
<urlset xmlns="http://www.sitemaps.org/schemas/sitemap/0.9"
        xmlns:xhtml="http://www.w3.org/1999/xhtml">
${entries.join("\n\n")}
</urlset>
`;

const out = resolve(
  dirname(fileURLToPath(import.meta.url)),
  "..",
  "public",
  "sitemap.xml",
);
mkdirSync(dirname(out), { recursive: true });
writeFileSync(out, xml);

console.log(
  `sitemap.xml: ${entries.length} URLs (${ROUTES.length} routes x ${LANGUAGES.length} languages), lastmod ${lastmod}`,
);
